import openingsJson from '../data/openings.json';
import { epdAfter, legalMoves, moveToUci, START_FEN, toEpd, type MoveRecord } from '../game/game';

/**
 * Offline opening book built from lichess-org/chess-openings (CC0), generated by
 * tools/build_openings.py. Positions are keyed by EPD so transpositions resolve correctly.
 */
export interface BookEntry {
  eco: string;
  name: string;
  /** "Family" is the part before the colon, e.g. "Sicilian Defense". */
  family: string;
  /** Everything after the colon, e.g. "Najdorf Variation, English Attack". May be empty. */
  variation: string;
  uci: string[];
  epd: string;
}

export type Volume = 'A' | 'B' | 'C' | 'D' | 'E';
export const VOLUMES: readonly Volume[] = ['A', 'B', 'C', 'D', 'E'];

interface RawBook {
  meta: { source: string; generatedAt: string; count: number };
  rows: [string, string, string, string][];
}

const raw = openingsJson as unknown as RawBook;

let entries: BookEntry[] | null = null;
let byEpd: Map<string, BookEntry> | null = null;

function splitName(name: string): { family: string; variation: string } {
  const i = name.indexOf(':');
  if (i === -1) return { family: name.trim(), variation: '' };
  return { family: name.slice(0, i).trim(), variation: name.slice(i + 1).trim() };
}

function load(): { entries: BookEntry[]; byEpd: Map<string, BookEntry> } {
  if (entries && byEpd) return { entries, byEpd };
  entries = raw.rows.map(([eco, name, uci, epd]) => ({
    eco,
    name,
    ...splitName(name),
    uci: uci ? uci.split(' ') : [],
    epd,
  }));
  byEpd = new Map();
  for (const e of entries) if (!byEpd.has(e.epd)) byEpd.set(e.epd, e);
  return { entries, byEpd };
}

export function bookMeta(): RawBook['meta'] {
  return raw.meta;
}

export function allOpenings(): readonly BookEntry[] {
  return load().entries;
}

/** Named opening for a position (by EPD), if any. */
export function lookupEpd(epd: string): BookEntry | undefined {
  return load().byEpd.get(epd);
}

export interface OpeningStatus {
  /** Last known named opening along the line (null before any book position). */
  opening: BookEntry | null;
  /** True when the current position itself is not in the book but an earlier one was. */
  outOfBook: boolean;
}

/**
 * Walk the played moves up to `ply` and return the most recent named position.
 * Mirrors what Lichess shows: the name sticks once you leave the book.
 */
export function openingForLine(
  moves: readonly MoveRecord[],
  ply: number,
  startFen: string = START_FEN,
): OpeningStatus {
  let last: BookEntry | null = lookupEpd(toEpd(startFen)) ?? null;
  let currentNamed = last !== null;
  for (let i = 0; i < Math.min(ply, moves.length); i++) {
    const hit = lookupEpd(moves[i].epd);
    if (hit) {
      last = hit;
      currentNamed = true;
    } else currentNamed = false;
  }
  return { opening: last, outOfBook: last !== null && !currentNamed };
}

export interface BookContinuation {
  uci: string;
  san: string;
  /** Name of the position reached directly by this move, if it is a named position. */
  opening: BookEntry | null;
  /** Number of named book lines that continue through this move. */
  lines: number;
  /** Shortest named line reached through this move (used as a label when `opening` is null). */
  example: BookEntry | null;
}

/**
 * Offline "popular continuations": legal moves from `fen` that either land on a named
 * position or lead into deeper named lines. `lineUci` is the actual move sequence played;
 * lines of transposed positions with the same EPD are considered too.
 */
export function bookContinuations(fen: string, lineUci: readonly string[]): BookContinuation[] {
  const { entries } = load();
  const epd = toEpd(fen);
  const prefixes = new Set<string>();
  prefixes.add(lineUci.join(' '));
  for (const e of entries) if (e.epd === epd) prefixes.add(e.uci.join(' '));

  const agg = new Map<string, { lines: number; example: BookEntry | null }>();
  for (const e of entries) {
    const line = e.uci.join(' ');
    for (const p of prefixes) {
      const matches = p === '' ? e.uci.length > 0 : line.startsWith(p + ' ');
      if (!matches) continue;
      const next = e.uci[p === '' ? 0 : p.split(' ').length];
      if (!next) continue;
      const a = agg.get(next) ?? { lines: 0, example: null };
      a.lines += 1;
      if (!a.example || e.uci.length < a.example.uci.length) a.example = e;
      agg.set(next, a);
      break;
    }
  }

  const out: BookContinuation[] = [];
  for (const m of legalMoves(fen)) {
    const uci = moveToUci(m);
    const after = epdAfter(fen, uci);
    const direct = after ? (lookupEpd(after) ?? null) : null;
    const a = agg.get(uci);
    if (!direct && !a) continue;
    out.push({
      uci,
      san: m.san,
      opening: direct,
      lines: a?.lines ?? 0,
      example: a?.example ?? null,
    });
  }
  out.sort(
    (x, y) =>
      y.lines - x.lines || Number(!!y.opening) - Number(!!x.opening) || x.san.localeCompare(y.san),
  );
  return out;
}

/** Case/diacritic-insensitive substring search over name, ECO and SAN-less UCI line. */
export function searchOpenings(query: string, limit = 200): BookEntry[] {
  const q = normalizeText(query);
  if (!q) return [];
  const { entries } = load();
  const out: BookEntry[] = [];
  for (const e of entries) {
    if (normalizeText(e.name).includes(q) || e.eco.toLowerCase() === q) {
      out.push(e);
      if (out.length >= limit) break;
    }
  }
  return out;
}

export function normalizeText(s: string): string {
  return s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[’']/g, '').trim();
}

export interface Family {
  name: string;
  volume: Volume;
  /** ECO range like "B20–B99" or a single code. */
  ecoRange: string;
  entries: BookEntry[];
}

let familiesCache: Family[] | null = null;

/** Openings grouped by family (name before the colon), ordered by first ECO code. */
export function families(): readonly Family[] {
  if (familiesCache) return familiesCache;
  const map = new Map<string, Family>();
  for (const e of load().entries) {
    const f = map.get(e.family);
    if (f) f.entries.push(e);
    else
      map.set(e.family, {
        name: e.family,
        volume: e.eco[0] as Volume,
        ecoRange: e.eco,
        entries: [e],
      });
  }
  for (const f of map.values()) {
    const codes = [...new Set(f.entries.map((e) => e.eco))].sort();
    f.ecoRange = codes.length > 1 ? `${codes[0]}–${codes[codes.length - 1]}` : codes[0];
    f.entries.sort(
      (a, b) =>
        a.uci.length - b.uci.length || a.eco.localeCompare(b.eco) || a.name.localeCompare(b.name),
    );
  }
  familiesCache = [...map.values()].sort(
    (a, b) => a.entries[0].eco.localeCompare(b.entries[0].eco) || a.name.localeCompare(b.name),
  );
  return familiesCache;
}

export function familiesByVolume(volume: Volume): Family[] {
  return families().filter((f) => f.volume === volume);
}

export function familyOf(name: string): Family | undefined {
  return families().find((f) => f.name === name);
}
